#
# Copyright The NOMAD Authors.
#
# This file is part of NOMAD. See https://nomad-lab.eu for further info.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from nomad.datamodel.metainfo.basesections import Measurement
from nomad.datamodel.metainfo.basesections import MeasurementResult
from structlog.stdlib import (
    BoundLogger,
)
from nomad.metainfo import (
    Package,
    Quantity,
    Section,
)
from nomad.datamodel.data import (
    ArchiveSection,
)

m_package = Package(name='nomad-measurements')


class XRDResult(MeasurementResult, ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()
    two_theta = Quantity(
        type=float,
        description='''
        The set 2 theta angle.
        ''',
        shape=["*"],
    )
    intensity = Quantity(
        type=float,
        description='''
        The measured intensity.
        ''',
        shape=["*"],
    )

    def normalize(self, archive, logger: BoundLogger) -> None:
        '''
        The normalizer for the `XRDResult` class.

        Args:
            archive (EntryArchive): The archive containing the section that is being
            normalized.
            logger (BoundLogger): A structlog logger.
        '''
        super(XRDResult, self).normalize(archive, logger)


class XRayDiffraction(Measurement, ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()
    method = Quantity(
        type=str,
        default="X-Ray Diffraction (XRD)",
    )

    def normalize(self, archive, logger: BoundLogger) -> None:
        '''
        The normalizer for the `XRayDiffraction` class.

        Args:
            archive (EntryArchive): The archive containing the section that is being
            normalized.
            logger (BoundLogger): A structlog logger.
        '''
        super(XRayDiffraction, self).normalize(archive, logger)


m_package.__init_metainfo__()
