name: Deploy MkDocs Site

on:
  push:
    branches:
      - main  # Set this to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.x'
          cache: pip

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material pymdown-extensions mkdocs-click

      - name: Build and deploy
        run: |
          mkdocs gh-deploy --force --remote-branch gh-pages
